name: Delete All Artifacts

on:
  push:
    branches:
      - main

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Delete All Artifacts
        run: |
          # Replace 'YOUR_TOKEN' with your personal access token
          TOKEN=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
          REPO_OWNER=oussamf1
          REPO_NAME=TravellingWizardMicroServices

          # Get a list of all artifacts
          ARTIFACTS=$(curl -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/packages/containers/container_id/artifacts")

          # Loop through artifacts and delete them
          for artifact in $(echo $ARTIFACTS | jq -r '.[] | .id'); do
            curl -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/packages/containers/container_id/artifacts/$artifact"
          done
